name: Markdown to Confluence
inputs:
  confluence_api_key:
    description: 'API key for communicating with Confluence REST API'
    required : true
  confluence_space: 
    description: 'Space in confluence to push docs to'
    required: true
  confluence_username: 
    description: 'Username for communicating with Confluence REST API'
    required: true
  repo_path: 
    description: 'Repo path for action to work on'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    PROJECT_PATH: "/github/workspace/" + ${{ inputs.repo_path }}
  
