name: Markdown to Confluence
inputs:
  args:
    description: 'Arguments for markdown tool'
    required: true
    default: 'key, space, username, path'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}
