name: Markdown to Confluence
inputs:
  INPUT_CONFLUENCE_API_KEY:
    description: 'API key for communicating with Confluence REST API'
    required : true
  INPUT_CONFLUENCE_SPACE: 
    description: 'Space in confluence to push docs to'
    required: true
  INPUT_CONFLUENCE_USERNAME: 
    description: 'Username for communicating with Confluence REST API'
    required: true
  PROJECT_PATH: 
    description: 'Repo path for action to work on'
    required: true
runs:
  using: docker
  image: Dockerfile
  
